services:
  api:
    image: node:18
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    command: node -r newrelic index.js
    depends_on:
      - mongo
    env_file:
      - ./.env
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./prod-data:/data/db
      - ./src/db/init:/docker-entrypoint-initdb.d:ro
    env_file:
      - ./.env
    command: 
      - '--logpath'
      - '/var/log/mongodb/mongod.log'